### ISSUE TITLE
When pulling the Pulumi Deployment image, support a custom default `registry`, `repository`, `name` and `tag`

### ISSUE THREAD

**Issue by aureq** [pulumi/customer-managed-deployment-agent#29]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great to be able to configure the customer managed deployment agent default behavior when it comes to pulling the custom executor image. Right now, the custom executor image is set at a stack level. This is all good until a customer has 10s or even 100s of stacks. If the image location changes, then all the stacks need to be updated accordingly.

To assist with this, the *default* configuration for the custom executor image could be set directly on the customer managed deployment agent instead. The YAML could look like this.

```yaml
executor_image:
  registry: ""
  repository: ""
  name: ""
  tag: ""
```

Here are the benefits to doing this
* If the image location changes, only the customer managed deployment agent needs to be updated, not every single stack deployment settings.
* Setting only `registry` would allow customers to pull images from their controlled registry. The default image `name:tag` would still be used though. For them, this means assurance of immutable images, container vulnerability scanning, with less configuration to perform for each stack.
* This would also allow customers to use registry proxies like offered by Go Harbor.
* It could even become possible to pull such images from other publicly accessible registries like `ghcr.io` or `quay.io` should Pulumi decide to also publish on those registries.

Of course, if the stack deployment settings specifies a custom image, then the specified one should be used as a priority.

### Affected area/feature

* Customer managed deployment agent

**Comment by rshade** [comment]
Can you attempt using this: `PULUMI_DEPLOY_DEFAULT_IMAGE_REFERENCE` environment variable?

**Comment by yenoromm** [comment]
> Can you attempt using this: `PULUMI_DEPLOY_DEFAULT_IMAGE_REFERENCE` environment variable? You can set it to the full path like: `ghcr.io/pulumi/pulumi-dotnet-8.0:3.137.0` and it should work fine

It is ignored by the agent and pulumi/pulumi:3.137.0 (as of writing this) is pulled. In the docs, this value seems to be for the self hosted Pulumi Cloud API service and not the agent pools

**Comment by rshade** [comment]
Thank you for trying.

**Comment by nyobe** [comment]
Since you already need to specify the agent pool as part of a stack's deployment settings, it seems like also specifying a custom executor image at the same time shouldn't be too much of an extra lift? Especially if you manage stack settings with the [pulumi-service provider](https://github.com/pulumi/pulumi-pulumiservice).  You could even use a shared ESC environment reference as the source of the deployment settings that are created to share across stacks.  Would something like this work?

**Comment by yenoromm** [comment]
We were doing something similar where we built the container in one stack and the image url was stored in an ESC env, this worked in theory but when it came to installing policy packs org wide, the pulumi python 3.12 image doesn't have node installed which we were using as our base image. We can't use the pulumi/pulumi image since this runs the 3.9 and fails with a lot of the more modern syntax (ie f strings with same quotes or pipes on return types like with the esc sdk as examples).

After discovering these limitations, we had to delete all policy packs, update each of the 50 stacks to an image that wouldn't fail since they use the pulumi service provider to manage its own deployment settings before finally applying the policy packs again. It is unsustainable to have this setting per stack. The user, for each and every stack, must 'remember' to fill that in and if they don't, a public image which is essentially pinned to 'latest' that has not been scanned in our registries is attempted to be pulled. This goes against several best practices and is blocked in the networks where the agents run. I would prefer no image to be the default over a public image unless explicitly set, but `PULUMI_DEPLOY_DEFAULT_IMAGE_REFERENCE` or as @aureq suggested since we see that with a lot of mature operators these days, a dictionary for each component of the image is a more sustainable enterprise solution.

**Comment by komalali** [comment]
> We can't use the pulumi/pulumi image since this runs python 3.9

As an aside, you can use a newer version of python in the pulumi/pulumi image by specifying a [version](https://github.com/pulumi/pulumi-docker-containers#python), FWIW.

**Comment by yenoromm** [comment]
> > We can't use the pulumi/pulumi image since this runs python 3.9
> 
> As an aside, you can use a newer version of python in the pulumi/pulumi image by specifying a [version](https://github.com/pulumi/pulumi-docker-containers#python), FWIW.

I did miss this piece of info and can confirm that worked, this does solve the python version. Thank you.

I still firmly believe that a default image should either be undefined or configurable per agent/agent pool either in the agent pool settings or with the agent's config to ensure images being used is more effectively managed in higher security environments.

**Comment by komalali** [comment]
> I still firmly believe that a default image should either be undefined or configurable per agent/agent pool either in the agent pool settings or with the agent's config to ensure images being used is more effectively managed in higher security environments.

I agree that the default image should be configurable at the agent pool or even the org level.  The mechanics of where exactly that configuration should live is still somewhat unclear, but I do agree that we should make this possible.

**Comment by yenoromm** [comment]
> I agree that the default image should be configurable at the agent pool or even the org level. The mechanics of where exactly that configuration should live is still somewhat unclear, but I do agree that we should make this possible.

I believe it should _not_ be an org level settings. The infrastructure may span multiple cloud providers or multiple environments, it is unlikely in complex organizations that there will be a single shared registry that all agents would pull from let alone have access to.

**Comment by rshade** [comment]
You should be able to use image: `v1.3.5`, and env var: PULUMI_DEPLOY_OVERRIDE_IMAGE_REFERENCE

**Comment by komalali** [comment]
> I believe it should not be an org level settings.

I think it's reasonable to allow hierarchical settings in this regard, with each level of granularity overriding the wider setting. Org > Agent Pool > Stack.

> You should be able to use image: v1.3.5, and env var: PULUMI_DEPLOY_OVERRIDE_IMAGE_REFERENCE

To be clear, this is an override, not a default. This will override the stack-level setting, rather than act as a fall-back in case no stack-level setting is defined. I think for your case, the end result is equivalent - but just wanted to call that out. To support the default we'll need additional work in the service.
